import "./globals.css";

export const metadata = {
  title: "Project Task Manager",
  description: "Project Task Manager | Generated by Next13",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
